### ISSUE TITLE
Most upvoted button not working

### ISSUE THREAD

**Issue by asmit203** [asmit203/TalkitOut#26]
![image](https://user-images.githubusercontent.com/92667287/205940154-63c9c669-05a4-45d0-8d4b-8287ec37b02c.png)
get this to work

**Comment by PrajwalDhungana** [comment]
This issue #26 is fixed by introducing anchor tags to the sidebar list with the links to the URL in urls.py
![image](https://user-images.githubusercontent.com/70053674/205973938-9162212f-9d6f-4c31-95d4-873012103c9e.png)
![image](https://user-images.githubusercontent.com/70053674/205974376-996c2859-1efe-4b8f-b93e-f7ba59056fa0.png)

**Comment by asmit203** [comment]
done by @PrajwalDhungana
